version: "3.2"
services:
  traefik:
    image: traefik:latest
    restart: always
    env_file: ../../stack.env
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=le"
      - "--entrypoints.websecure.http.tls.domains[0].main=0x08.in"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.0x08.in,*.app.0x08.in,*.internal.0x08.in"
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.le.acme.email=reg@0x08.in"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    volumes:
      - /srv/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    networks:
      - net-traefik
    labels:
      - "traefik.enable=true"

      # Traefik Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.app.0x08.in`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${DASHBOARD_BASIC_AUTH}"
      - "traefik.http.services.traefik-dashboard-svc.loadbalancer.server.port=80"

      # Permanent Teleport redirect
      - "traefik.http.routers.teleport.entrypoints=websecure"
      - "traefik.http.routers.teleport.rule=Host(`teleport.0x08.in`)"
      - "traefik.http.routers.teleport.middlewares=redirect-teleport"
      - "traefik.http.middlewares.redirect-teleport.redirectregex.regex=(.)*"
      - "traefik.http.middlewares.redirect-teleport.redirectregex.replacement=https://teleport.0x08.in:3080"
      - "traefik.http.middlewares.redirect-regex.redirectregex.permanent=true"

      # NTP server redirect to NTP Pool Project
      - "traefik.http.routers.timeserver.entrypoints=websecure"
      - "traefik.http.routers.timeserver.rule=Host(`time.0x08.in`)"
      - "traefik.http.routers.timeserver.middlewares=redirect-timeserver"
      - "traefik.http.middlewares.redirect-timeserver.redirectregex.regex=(.)*"
      - "traefik.http.middlewares.redirect-timeserver.redirectregex.replacement=https://www.ntppool.org"

networks:
  net-traefik:
    external: true
